minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.10
fabric_version=0.115.3+1.21.1

modGroup=it.kada49
modName=DisableBurningAnimation
modVersion=1.1

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureoncommand=true
org.gradle.parallel.threads=4
org.gradle.jvmargs=-Xmx4G
